project:
  type: website
  output-dir: docs

website:
  title: "Arna Ramadhan"
  page-footer: "Â© Arna Ramadhan. 2026."
  back-to-top-navigation: true
  
  google-analytics:
    tracking-id: "G-E67S774T4Q"
    anonymize-ip: true
  cookie-consent: true
  
  navbar:
    left:
      - href: index.qmd
        text: Beranda
      - href: kelas/jadwal-kelas.qmd
        text: Kelas

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



